const VERSION = "20260805-3";

const sections = [
  ["where-intelligence", "Where is the intelligence?", "¿Dónde está la inteligencia?"],
  ["ai-definition", "A practical definition of AI", "Una definición práctica de IA"],
  ["rules-patterns", "Rules vs. learned patterns", "Reglas vs. patrones aprendidos"],
  ["field-map", "AI, ML, and Deep Learning", "IA, ML y Deep Learning"],
  ["learning-definition", "What learning means", "Qué significa aprender"],
  ["data-language", "Data language", "Lenguaje de datos"],
  ["learning-types", "Three ways to learn", "Tres formas de aprender"],
  ["lifecycle", "Model life cycle", "Ciclo de vida del modelo"],
  ["evaluation", "Evaluation and metrics", "Evaluación y métricas"],
  ["generalization", "Generalization and responsibility", "Generalización y responsabilidad"],
];

const text = {
  en: {
    pageTitle: "Class 01 | AI and Machine Learning",
    navHome: "Home",
    navConcepts: "Concepts",
    navLab: "Lab",
    navCheck: "Check",
    classLabel: "Class 01",
    heroTitle: "AI and Machine Learning",
    heroText: "Learn how intelligent systems move from programmed rules to patterns adjusted from data.",
    startClass: "Start class",
    openLab: "Open lab",
    outcomeLabel: "Learning outcome",
    outcomeTitle: "What you should be able to explain",
    outcome1Title: "Field map",
    outcome1Text: "Distinguish Artificial Intelligence, Machine Learning, and Deep Learning.",
    outcome2Title: "Problem framing",
    outcome2Text: "Recognize when a problem can be formulated as a learning problem.",
    outcome3Title: "Data language",
    outcome3Text: "Identify observations, features, labels, algorithms, models, training, and inference.",
    outcome4Title: "Responsible use",
    outcome4Text: "Explain why prediction supports decisions but does not replace human responsibility.",
    conceptsLabel: "Concepts",
    conceptsTitle: "Foundations for learning systems",
    indexTitle: "Jump to",
    s1Title: "Where is the intelligence?",
    s1Text1: "An alarm set for 6:00 a.m. follows a fixed instruction. A traffic light that adapts to vehicle flow uses information from the environment. A system that estimates academic risk from historical records learns a pattern from data.",
    s1Text2: "In engineering, intelligence is evaluated through observable capabilities: perceiving information, representing a problem, reasoning about alternatives, learning from experience, making decisions, and acting toward an objective.",
    s1Callout: "A system is not intelligent because it looks human. It is evaluated by the quality of its decisions within an objective and a context.",
    dPerspectiveCenter: "Intelligent system",
    dPerspective1Title: "Think like humans",
    dPerspective1Text: "Model memory, reasoning, and learning.",
    dPerspective2Title: "Think rationally",
    dPerspective2Text: "Use logic to reach valid conclusions.",
    dPerspective3Title: "Act like humans",
    dPerspective3Text: "Produce behavior that is hard to distinguish from human behavior.",
    dPerspective4Title: "Act rationally",
    dPerspective4Text: "Choose actions that increase the chance of reaching a goal.",
    s2Title: "A practical definition of AI",
    s2Text1: "An AI system is machine-based. It receives inputs, uses explicit or implicit objectives, infers how to produce outputs, and can influence physical or virtual environments through predictions, content, recommendations, or decisions.",
    s2Text2: "Automation is not automatically AI. A fixed macro can copy data without learning. AI appears when the system includes perception, reasoning, search, learning, or decision mechanisms beyond a rigid sequence of instructions.",
    aiComp1Title: "Inputs",
    aiComp1Text: "Data, signals, images, text, measurements, or states.",
    aiComp2Title: "Objectives",
    aiComp2Text: "Criteria that orient behavior.",
    aiComp3Title: "Inference",
    aiComp3Text: "Transformation from input to estimate, class, recommendation, or action.",
    aiComp4Title: "Influence",
    aiComp4Text: "The output can guide a person or affect an environment.",
    s3Title: "Rules programmed vs. patterns learned",
    s3Text1: "In traditional programming, the rule is written by the developer. In Machine Learning, examples, a task, and a performance measure are supplied so an algorithm can adjust a model.",
    s3Text2: "Code does not disappear. It collects data, prepares it, selects algorithms, trains models, calculates metrics, and integrates predictions into applications. What changes is the origin of the decision function.",
    dCompare1Title: "Traditional programming",
    dCompareData: "Data",
    dCompareRules: "Rules",
    dCompareResult: "Result",
    dCompare1Text: "The programmer explicitly writes the logic.",
    dCompare2Title: "Machine Learning",
    dCompareExamples: "Examples",
    dCompareAlgorithm: "Algorithm",
    dCompareModel: "Model",
    dCompare2Text: "The algorithm adjusts a function from examples.",
    s4Title: "AI, Machine Learning, and Deep Learning",
    s4Text1: "Artificial Intelligence is the broad field. Machine Learning is a subfield focused on improving behavior through data or experience. Deep Learning is a family of Machine Learning methods based on neural networks with many layers.",
    s4Text2: "This hierarchy avoids three common mistakes: not all AI uses ML, not all ML uses deep networks, and not every practical problem needs a neural network.",
    dMapAI: "Artificial Intelligence",
    dMapAIText: "Perceive, reason, plan, decide, and learn.",
    dMapScope1: "Broad field",
    dMapML: "Machine Learning",
    dMapMLText: "Models adjusted with data.",
    dMapScope2: "Subfield",
    dMapDL: "Deep Learning",
    dMapDLText: "Neural networks with multiple layers.",
    dMapScope3: "Family of methods",
    s5Title: "What does it mean for a machine to learn?",
    s5Text1: "A program learns from experience when its performance on a task improves according to a defined measure. This forces three questions: what task should the system perform, what experience does it learn from, and how will improvement be measured?",
    s5Text2: "Learning does not mean understanding like a person. A model can capture a statistical regularity without knowing its cause.",
    learnCol1: "Element",
    learnCol2: "Question",
    learnCol3: "Academic example",
    taskLabel: "Task",
    taskQuestion: "What should the system do?",
    taskExample: "Classify whether a student is at risk.",
    experienceLabel: "Experience",
    experienceQuestion: "What information does it learn from?",
    experienceExample: "Historical attendance, grades, and final outcome.",
    performanceLabel: "Performance",
    performanceQuestion: "How do we decide it improved?",
    performanceExample: "Recall, precision, and review of false alerts.",
    s6Title: "The basic language of data",
    s6Text1: "A dataset is a structured collection of examples. In a table, each row usually represents an observation and each column represents a variable.",
    s6Text2: "Features are the input variables used by the model. The label, objective, or target is the value to predict in supervised learning.",
    dDataAttendance: "Attendance",
    dDataTasks: "Tasks",
    dDataGrade: "First grade",
    dDataPassed: "Passed",
    yes: "Yes",
    no: "No",
    dDataRow: "Row = observation",
    dDataColumns: "Columns = features",
    dDataTarget: "Target = label",
    s7Title: "Three ways to learn",
    s7Text1: "Machine Learning paradigms differ by the signal available to adjust behavior. Supervised learning has known answers, unsupervised learning searches for structure, and reinforcement learning uses accumulated consequences.",
    dType1Signal: "Data + label",
    dType1Title: "Supervised",
    dType1Text: "Learns from examples that include the correct answer.",
    dType1Examples: "Classification, regression",
    dType2Signal: "Only data",
    dType2Title: "Unsupervised",
    dType2Text: "Finds structure without a predefined answer.",
    dType2Examples: "Clustering, anomaly detection",
    dType3Signal: "Experience",
    dType3Title: "Reinforcement",
    dType3Text: "Acts, receives rewards or penalties, and learns a policy.",
    dType3Examples: "Agent, action, reward",
    s8Title: "The life cycle of a model",
    s8Text1: "A Machine Learning project does not start by selecting an algorithm. It starts by defining a decision and continues after the model is used.",
    s8Text2: "A valuable model is not simply the one with the highest number in a lab. It is the one that improves a real decision without creating unacceptable harm.",
    life1: "Problem",
    life2: "Data",
    life3: "Prepare",
    life4: "Train",
    life5: "Evaluate",
    life6: "Use",
    life7: "Monitor",
    s9Title: "Training, validation, testing, and metrics",
    s9Text1: "Evaluating with the same data used for training gives an optimistic view. Training adjusts parameters, validation compares configurations, and testing estimates final performance once design decisions are closed.",
    s9Text2: "Metrics must match the impact of the decision. In academic risk, missing a real case can be more costly than creating an extra alert.",
    metricAccuracy: "Overall proportion of correct predictions.",
    metricPrecisionTitle: "Precision",
    metricPrecision: "Of all alerts, how many were real?",
    metricRecall: "Of all real risk cases, how many were detected?",
    metricMae: "Average absolute error for numeric predictions.",
    s10Title: "Generalization and responsible decisions",
    s10Text1: "Generalizing means applying a learned pattern to new cases from the same problem. Underfitting is too simple, overfitting memorizes noise, and good fit captures the pattern that remains useful outside training data.",
    s10Text2: "A prediction is evidence for a decision, not an automatic sentence. Responsible use combines technical quality, human review, privacy, transparency, and institutional accountability.",
    fitUnder: "Underfitting",
    fitUnderText: "Too simple",
    fitGood: "Good fit",
    fitGoodText: "Captures the pattern",
    fitOver: "Overfitting",
    fitOverText: "Memorizes noise",
    labLabel: "Mini lab",
    labTitle: "From dataset to prediction",
    labIntro: "This artificial example shows the flow of a supervised classification task. It is useful for learning the vocabulary, but it is not evidence for a real academic decision.",
    labStep1: "Create a small dataset.",
    labStep2: "Separate features and target.",
    labStep3: "Split training and test data.",
    labStep4: "Train a decision tree.",
    labStep5: "Evaluate and predict a new case.",
    checkLabel: "Study check",
    checkTitle: "Apply the concepts",
    checkCase: "A company wants to reduce server failures. It has temperature, CPU use, memory use, disk errors, and records indicating whether a failure occurred during the next 24 hours.",
    q1: "What is the observation unit?",
    q2: "Which variables are features?",
    q3: "What is the label?",
    q4: "Is this supervised, unsupervised, or reinforcement learning?",
    q5: "Is the output classification or regression?",
    q6: "What information could create data leakage?",
    q7: "Which error would be more costly: a false alarm or missing a real failure?",
    q8: "How could the prediction be used without becoming an automatic decision?",
    referencesLabel: "References",
    referencesTitle: "Recommended sources",
    footerText: "Generative AI course notebook",
  },
  es: {
    pageTitle: "Clase 01 | IA y Machine Learning",
    navHome: "Inicio",
    navConcepts: "Conceptos",
    navLab: "Laboratorio",
    navCheck: "Verificación",
    classLabel: "Clase 01",
    heroTitle: "IA y Machine Learning",
    heroText: "Aprende cómo los sistemas inteligentes pasan de reglas programadas a patrones ajustados desde datos.",
    startClass: "Empezar clase",
    openLab: "Abrir laboratorio",
    outcomeLabel: "Resultado de aprendizaje",
    outcomeTitle: "Lo que deberías poder explicar",
    outcome1Title: "Mapa del campo",
    outcome1Text: "Distinguir Inteligencia Artificial, Machine Learning y Deep Learning.",
    outcome2Title: "Formulación del problema",
    outcome2Text: "Reconocer cuándo un problema puede formularse como un problema de aprendizaje.",
    outcome3Title: "Lenguaje de datos",
    outcome3Text: "Identificar observaciones, características, etiquetas, algoritmos, modelos, entrenamiento e inferencia.",
    outcome4Title: "Uso responsable",
    outcome4Text: "Explicar por qué una predicción apoya decisiones, pero no reemplaza la responsabilidad humana.",
    conceptsLabel: "Conceptos",
    conceptsTitle: "Fundamentos de los sistemas que aprenden",
    indexTitle: "Ir a",
    s1Title: "¿Dónde está la inteligencia?",
    s1Text1: "Una alarma puesta para las 6:00 a. m. sigue una instrucción fija. Un semáforo que se adapta al flujo vehicular usa información del entorno. Un sistema que estima riesgo académico desde registros históricos aprende un patrón a partir de datos.",
    s1Text2: "En ingeniería, la inteligencia se evalúa mediante capacidades observables: percibir información, representar un problema, razonar sobre alternativas, aprender de la experiencia, tomar decisiones y actuar hacia un objetivo.",
    s1Callout: "Un sistema no es inteligente porque parezca humano. Se evalúa por la calidad de sus decisiones dentro de un objetivo y un contexto.",
    dPerspectiveCenter: "Sistema inteligente",
    dPerspective1Title: "Pensar como humanos",
    dPerspective1Text: "Modelar memoria, razonamiento y aprendizaje.",
    dPerspective2Title: "Pensar racionalmente",
    dPerspective2Text: "Usar lógica para llegar a conclusiones válidas.",
    dPerspective3Title: "Actuar como humanos",
    dPerspective3Text: "Producir conductas difíciles de distinguir de las humanas.",
    dPerspective4Title: "Actuar racionalmente",
    dPerspective4Text: "Elegir acciones que aumentan la probabilidad de alcanzar un objetivo.",
    s2Title: "Una definición práctica de IA",
    s2Text1: "Un sistema de IA está basado en máquinas. Recibe entradas, usa objetivos explícitos o implícitos, infiere cómo producir salidas y puede influir en entornos físicos o virtuales mediante predicciones, contenido, recomendaciones o decisiones.",
    s2Text2: "Automatizar no significa usar IA automáticamente. Una macro fija puede copiar datos sin aprender. La IA aparece cuando el sistema incluye percepción, razonamiento, búsqueda, aprendizaje o decisión más allá de una secuencia rígida de instrucciones.",
    aiComp1Title: "Entradas",
    aiComp1Text: "Datos, señales, imágenes, texto, mediciones o estados.",
    aiComp2Title: "Objetivos",
    aiComp2Text: "Criterios que orientan el comportamiento.",
    aiComp3Title: "Inferencia",
    aiComp3Text: "Transformación de entrada a estimación, clase, recomendación o acción.",
    aiComp4Title: "Influencia",
    aiComp4Text: "La salida puede guiar a una persona o afectar un entorno.",
    s3Title: "Reglas programadas vs. patrones aprendidos",
    s3Text1: "En la programación tradicional, la regla la escribe quien desarrolla. En Machine Learning, se entregan ejemplos, una tarea y una medida de desempeño para que un algoritmo ajuste un modelo.",
    s3Text2: "El código no desaparece. Recolecta datos, los prepara, selecciona algoritmos, entrena modelos, calcula métricas e integra predicciones en aplicaciones. Lo que cambia es el origen de la función de decisión.",
    dCompare1Title: "Programación tradicional",
    dCompareData: "Datos",
    dCompareRules: "Reglas",
    dCompareResult: "Resultado",
    dCompare1Text: "La lógica se escribe explícitamente.",
    dCompare2Title: "Machine Learning",
    dCompareExamples: "Ejemplos",
    dCompareAlgorithm: "Algoritmo",
    dCompareModel: "Modelo",
    dCompare2Text: "El algoritmo ajusta una función desde ejemplos.",
    s4Title: "IA, Machine Learning y Deep Learning",
    s4Text1: "La Inteligencia Artificial es el campo amplio. Machine Learning es un subcampo enfocado en mejorar el comportamiento mediante datos o experiencia. Deep Learning es una familia de métodos de Machine Learning basada en redes neuronales con muchas capas.",
    s4Text2: "Esta jerarquía evita tres errores frecuentes: no toda IA usa ML, no todo ML usa redes profundas y no todo problema práctico necesita una red neuronal.",
    dMapAI: "Inteligencia Artificial",
    dMapAIText: "Percibir, razonar, planificar, decidir y aprender.",
    dMapScope1: "Campo amplio",
    dMapML: "Machine Learning",
    dMapMLText: "Modelos ajustados con datos.",
    dMapScope2: "Subcampo",
    dMapDL: "Deep Learning",
    dMapDLText: "Redes neuronales con múltiples capas.",
    dMapScope3: "Familia de métodos",
    s5Title: "¿Qué significa que una máquina aprenda?",
    s5Text1: "Un programa aprende de la experiencia cuando su desempeño en una tarea mejora según una medida definida. Esto obliga a responder tres preguntas: qué tarea debe realizar el sistema, de qué experiencia aprende y cómo se medirá la mejora.",
    s5Text2: "Aprender no significa comprender como una persona. Un modelo puede capturar una regularidad estadística sin conocer su causa.",
    learnCol1: "Elemento",
    learnCol2: "Pregunta",
    learnCol3: "Ejemplo académico",
    taskLabel: "Tarea",
    taskQuestion: "¿Qué debe hacer el sistema?",
    taskExample: "Clasificar si un estudiante está en riesgo.",
    experienceLabel: "Experiencia",
    experienceQuestion: "¿De qué información aprende?",
    experienceExample: "Asistencia, notas y resultado final históricos.",
    performanceLabel: "Desempeño",
    performanceQuestion: "¿Cómo decidimos si mejoró?",
    performanceExample: "Recall, precisión y revisión de falsas alertas.",
    s6Title: "El lenguaje básico de los datos",
    s6Text1: "Un dataset es una colección estructurada de ejemplos. En una tabla, cada fila suele representar una observación y cada columna representa una variable.",
    s6Text2: "Las características son las variables de entrada usadas por el modelo. La etiqueta, objetivo o target es el valor que se busca predecir en aprendizaje supervisado.",
    dDataAttendance: "Asistencia",
    dDataTasks: "Tareas",
    dDataGrade: "Primer corte",
    dDataPassed: "Aprobó",
    yes: "Sí",
    no: "No",
    dDataRow: "Fila = observación",
    dDataColumns: "Columnas = características",
    dDataTarget: "Objetivo = etiqueta",
    s7Title: "Tres formas de aprender",
    s7Text1: "Los paradigmas de Machine Learning se diferencian por la señal disponible para ajustar el comportamiento. El aprendizaje supervisado tiene respuestas conocidas, el no supervisado busca estructura y el aprendizaje por refuerzo usa consecuencias acumuladas.",
    dType1Signal: "Datos + etiqueta",
    dType1Title: "Supervisado",
    dType1Text: "Aprende con ejemplos que incluyen la respuesta correcta.",
    dType1Examples: "Clasificación, regresión",
    dType2Signal: "Solo datos",
    dType2Title: "No supervisado",
    dType2Text: "Encuentra estructura sin una respuesta previamente definida.",
    dType2Examples: "Clustering, anomalías",
    dType3Signal: "Experiencia",
    dType3Title: "Por refuerzo",
    dType3Text: "Actúa, recibe recompensas o penalizaciones y aprende una política.",
    dType3Examples: "Agente, acción, recompensa",
    s8Title: "El ciclo de vida de un modelo",
    s8Text1: "Un proyecto de Machine Learning no empieza seleccionando un algoritmo. Empieza definiendo una decisión y continúa después de usar el modelo.",
    s8Text2: "Un modelo valioso no es simplemente el que obtiene la cifra más alta en un laboratorio. Es el que mejora una decisión real sin crear daños inaceptables.",
    life1: "Problema",
    life2: "Datos",
    life3: "Preparar",
    life4: "Entrenar",
    life5: "Evaluar",
    life6: "Usar",
    life7: "Monitorear",
    s9Title: "Entrenamiento, validación, prueba y métricas",
    s9Text1: "Evaluar con los mismos datos usados para entrenar da una visión optimista. El entrenamiento ajusta parámetros, la validación compara configuraciones y la prueba estima el desempeño final cuando las decisiones de diseño ya están cerradas.",
    s9Text2: "Las métricas deben corresponder al impacto de la decisión. En riesgo académico, dejar pasar un caso real puede costar más que generar una alerta adicional.",
    metricAccuracy: "Proporción total de predicciones correctas.",
    metricPrecisionTitle: "Precisión",
    metricPrecision: "De todas las alertas, ¿cuántas eran reales?",
    metricRecall: "De todos los casos reales de riesgo, ¿cuántos fueron detectados?",
    metricMae: "Promedio del error absoluto en predicciones numéricas.",
    s10Title: "Generalización y decisiones responsables",
    s10Text1: "Generalizar significa aplicar un patrón aprendido a casos nuevos del mismo problema. El subajuste es demasiado simple, el sobreajuste memoriza ruido y el buen ajuste captura el patrón que sigue siendo útil fuera de los datos de entrenamiento.",
    s10Text2: "Una predicción es evidencia para una decisión, no una sentencia automática. El uso responsable combina calidad técnica, revisión humana, privacidad, transparencia y responsabilidad institucional.",
    fitUnder: "Subajuste",
    fitUnderText: "Demasiado simple",
    fitGood: "Buen ajuste",
    fitGoodText: "Captura el patrón",
    fitOver: "Sobreajuste",
    fitOverText: "Memoriza ruido",
    labLabel: "Mini laboratorio",
    labTitle: "Del dataset a la predicción",
    labIntro: "Este ejemplo artificial muestra el flujo de una tarea de clasificación supervisada. Sirve para aprender el vocabulario, pero no es evidencia para una decisión académica real.",
    labStep1: "Crear un dataset pequeño.",
    labStep2: "Separar características y objetivo.",
    labStep3: "Dividir datos de entrenamiento y prueba.",
    labStep4: "Entrenar un árbol de decisión.",
    labStep5: "Evaluar y predecir un caso nuevo.",
    checkLabel: "Verificación",
    checkTitle: "Aplica los conceptos",
    checkCase: "Una empresa quiere reducir las fallas de sus servidores. Tiene temperatura, uso de CPU, uso de memoria, errores de disco y registros que indican si ocurrió una falla durante las siguientes 24 horas.",
    q1: "¿Cuál es la unidad de observación?",
    q2: "¿Qué variables son características?",
    q3: "¿Cuál es la etiqueta?",
    q4: "¿Es aprendizaje supervisado, no supervisado o por refuerzo?",
    q5: "¿La salida es clasificación o regresión?",
    q6: "¿Qué información podría producir fuga de datos?",
    q7: "¿Qué error sería más costoso: una falsa alarma o no detectar una falla real?",
    q8: "¿Cómo podría usarse la predicción sin convertirla en una decisión automática?",
    referencesLabel: "Referencias",
    referencesTitle: "Fuentes recomendadas",
    footerText: "Cuaderno del curso de IA Generativa",
  },
};

function render(lang) {
  const dictionary = text[lang];
  document.documentElement.lang = lang;
  document.title = dictionary.pageTitle;

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const value = dictionary[node.dataset.i18n];
    if (value) node.textContent = value;
  });

  document.querySelectorAll(".lang-button").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.lang === lang);
  });

  document.querySelectorAll("[data-lang-only]").forEach((node) => {
    node.classList.toggle("is-visible", node.dataset.langOnly === lang);
  });

  document.getElementById("classIndex").innerHTML = sections
    .map((section, index) => {
      const title = lang === "es" ? section[2] : section[1];
      return `<a href="#${section[0]}"><span>${String(index + 1).padStart(2, "0")}</span>${title}</a>`;
    })
    .join("");
}

document.querySelectorAll(".lang-button").forEach((button) => {
  button.addEventListener("click", () => {
    const lang = button.dataset.lang;
    localStorage.setItem("genai-language", lang);
    render(lang);
  });
});

render(localStorage.getItem("genai-language") || "en");

console.info(`Class 01 assets version ${VERSION}`);
